// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cloud1': string;
  'cloud2': string;
  'pikachu': string;
  'pocketBallBig': string;
  'pocketBallSmall': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
