// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'images': string;
  'info': string;
  'info__text': string;
  'info__title': string;
  'info__title_bold': string;
  'root': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
