// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'logo': string;
  'menu': string;
  'menu__item': string;
  'root': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
