// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bodyWrapper': string;
  'pokemonsWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
